// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhgpsgtnkkyijqrdjgwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oZ3BzZ3Rua2t5aWpxcmRqZ3duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjUwOTEsImV4cCI6MjA3MzEwMTA5MX0.8vBU5aEOJ18OHfw-xkrtIjxZGCT9gnbqXNwp7U8YwKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});